@HttpQuery_HostAddress = http://localhost:5254

GET {{HttpQuery_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{HttpQuery_HostAddress}}/weatherforecast/
Accept: application/json

###
